export interface VerbConjugation {
  id: number;
  hungarian: string;
  german_infinitive: string;
  german_present_first_person: string;
  german_past_participle: string;
}

export const verbs: VerbConjugation[] = [
  {
    id: 1,
    hungarian: "sütni",
    german_infinitive: "backen",
    german_present_first_person: "backte",
    german_past_participle: "gebacken",
  },
  {
    id: 2,
    hungarian: "parancsolni",
    german_infinitive: "befehlen",
    german_present_first_person: "befahl",
    german_past_participle: "befohlen",
  },
  {
    id: 3,
    hungarian: "kezdeni",
    german_infinitive: "beginnen",
    german_present_first_person: "begann",
    german_past_participle: "begonnen",
  },
  {
    id: 4,
    hungarian: "hívni; nevezni",
    german_infinitive: "heißen",
    german_present_first_person: "hieß",
    german_past_participle: "geheißen",
  },
  {
    id: 5,
    hungarian: "hajlítani; kanyarítani",
    german_infinitive: "biegen",
    german_present_first_person: "bog",
    german_past_participle: "gebogen",
  },
  {
    id: 6,
    hungarian: "kínálni",
    german_infinitive: "bieten",
    german_present_first_person: "bot",
    german_past_participle: "geboten",
  },
  {
    id: 7,
    hungarian: "maradni",
    german_infinitive: "bleiben",
    german_present_first_person: "blieb",
    german_past_participle: "geblieben",
  },
  {
    id: 8,
    hungarian: "törni",
    german_infinitive: "brechen",
    german_present_first_person: "brach",
    german_past_participle: "gebrochen",
  },
  {
    id: 9,
    hungarian: "fogadni",
    german_infinitive: "empfangen",
    german_present_first_person: "empfing",
    german_past_participle: "empfangen",
  },
  {
    id: 10,
    hungarian: "ajánlani",
    german_infinitive: "empfehlen",
    german_present_first_person: "empfahl",
    german_past_participle: "empfohlen",
  },
  {
    id: 11,
    hungarian: "érezni",
    german_infinitive: "empfinden",
    german_present_first_person: "empfand",
    german_past_participle: "empfunden",
  },
  {
    id: 12,
    hungarian: "enni",
    german_infinitive: "essen",
    german_present_first_person: "aß",
    german_past_participle: "gegessen",
  },
  {
    id: 13,
    hungarian: "utazni; vezetni",
    german_infinitive: "fahren",
    german_present_first_person: "fuhr",
    german_past_participle: "gefahren",
  },
  {
    id: 14,
    hungarian: "fogni",
    german_infinitive: "fangen",
    german_present_first_person: "fing",
    german_past_participle: "gefangen",
  },
  {
    id: 15,
    hungarian: "találni",
    german_infinitive: "finden",
    german_present_first_person: "fand",
    german_past_participle: "gefunden",
  },
  {
    id: 16,
    hungarian: "repülni",
    german_infinitive: "fliegen",
    german_present_first_person: "flog",
    german_past_participle: "geflogen",
  },
  {
    id: 17,
    hungarian: "menekülni",
    german_infinitive: "fliehen",
    german_present_first_person: "floh",
    german_past_participle: "geflohen",
  },
  {
    id: 18,
    hungarian: "folyni",
    german_infinitive: "fließen",
    german_present_first_person: "floss",
    german_past_participle: "geflossen",
  },
  {
    id: 19,
    hungarian: "zabálni",
    german_infinitive: "fressen",
    german_present_first_person: "fraß",
    german_past_participle: "gefressen",
  },
  {
    id: 20,
    hungarian: "fázni; megfagyni",
    german_infinitive: "frieren",
    german_present_first_person: "fror",
    german_past_participle: "gefroren",
  },
  {
    id: 21,
    hungarian: "adni",
    german_infinitive: "geben",
    german_present_first_person: "gab",
    german_past_participle: "gegeben",
  },
  {
    id: 22,
    hungarian: "menni",
    german_infinitive: "gehen",
    german_present_first_person: "ging",
    german_past_participle: "gegangen",
  },
  {
    id: 23,
    hungarian: "sikerülni",
    german_infinitive: "gelingen",
    german_present_first_person: "gelang",
    german_past_participle: "gelungen",
  },
  {
    id: 24,
    hungarian: "érvényesnek lenni",
    german_infinitive: "gelten",
    german_present_first_person: "galt",
    german_past_participle: "gegolten",
  },
  {
    id: 25,
    hungarian: "élvezni",
    german_infinitive: "genießen",
    german_present_first_person: "genoss",
    german_past_participle: "genossen",
  },
  {
    id: 26,
    hungarian: "jutni; kerülni",
    german_infinitive: "geraten",
    german_present_first_person: "geriet",
    german_past_participle: "geraten",
  },
  {
    id: 27,
    hungarian: "történni",
    german_infinitive: "geschehen",
    german_present_first_person: "geschah",
    german_past_participle: "geschehen",
  },
  {
    id: 28,
    hungarian: "nyerni",
    german_infinitive: "gewinnen",
    german_present_first_person: "gewann",
    german_past_participle: "gewonnen",
  },
  {
    id: 29,
    hungarian: "öntözni; önteni",
    german_infinitive: "gießen",
    german_present_first_person: "goss",
    german_past_participle: "gegossen",
  },
  {
    id: 30,
    hungarian: "hasonlítani",
    german_infinitive: "gleichen",
    german_present_first_person: "glich",
    german_past_participle: "geglichen",
  },
  {
    id: 31,
    hungarian: "csúszni",
    german_infinitive: "gleiten",
    german_present_first_person: "glitt",
    german_past_participle: "geglitten",
  },
  {
    id: 32,
    hungarian: "ásni",
    german_infinitive: "graben",
    german_present_first_person: "grub",
    german_past_participle: "gegraben",
  },
  {
    id: 33,
    hungarian: "megfogni",
    german_infinitive: "greifen",
    german_present_first_person: "griff",
    german_past_participle: "gegriffen",
  },
  {
    id: 34,
    hungarian: "tartani",
    german_infinitive: "halten",
    german_present_first_person: "hielt",
    german_past_participle: "gehalten",
  },
  {
    id: 35,
    hungarian: "lógni; függni",
    german_infinitive: "hängen",
    german_present_first_person: "hing",
    german_past_participle: "gehangen",
  },
  {
    id: 36,
    hungarian: "emelni",
    german_infinitive: "heben",
    german_present_first_person: "hob",
    german_past_participle: "gehoben",
  },
  {
    id: 37,
    hungarian: "segíteni",
    german_infinitive: "helfen",
    german_present_first_person: "half",
    german_past_participle: "geholfen",
  },
];
