export interface VerbConjugation {
  id: number;
  hungarian: string;
  german_infinitive: string;
  german_present_first_person: string;
  german_past_participle: string;
  auxiliary_verb: "haben" | "sein" | "haben/sein";
}

export const verbs: VerbConjugation[] = [
  {
    id: 1,
    hungarian: "sütni",
    german_infinitive: "backen",
    german_present_first_person: "backte",
    german_past_participle: "gebacken",
    auxiliary_verb: "haben",
  },
  {
    id: 2,
    hungarian: "parancsolni",
    german_infinitive: "befehlen",
    german_present_first_person: "befahl",
    german_past_participle: "befohlen",
    auxiliary_verb: "haben",
  },
  {
    id: 3,
    hungarian: "kezdeni",
    german_infinitive: "beginnen",
    german_present_first_person: "begann",
    german_past_participle: "begonnen",
    auxiliary_verb: "haben",
  },
  {
    id: 4,
    hungarian: "hívni; nevezni",
    german_infinitive: "heißen",
    german_present_first_person: "hieß",
    german_past_participle: "geheißen",
    auxiliary_verb: "haben",
  },
  {
    id: 5,
    hungarian: "hajlítani; kanyarítani",
    german_infinitive: "biegen",
    german_present_first_person: "bog",
    german_past_participle: "gebogen",
    auxiliary_verb: "haben",
  },
  {
    id: 6,
    hungarian: "kínálni",
    german_infinitive: "bieten",
    german_present_first_person: "bot",
    german_past_participle: "geboten",
    auxiliary_verb: "haben",
  },
  {
    id: 7,
    hungarian: "maradni",
    german_infinitive: "bleiben",
    german_present_first_person: "blieb",
    german_past_participle: "geblieben",
    auxiliary_verb: "sein",
  },
  {
    id: 8,
    hungarian: "törni",
    german_infinitive: "brechen",
    german_present_first_person: "brach",
    german_past_participle: "gebrochen",
    auxiliary_verb: "haben",
  },
  {
    id: 9,
    hungarian: "fogadni",
    german_infinitive: "empfangen",
    german_present_first_person: "empfing",
    german_past_participle: "empfangen",
    auxiliary_verb: "haben",
  },
  {
    id: 10,
    hungarian: "ajánlani",
    german_infinitive: "empfehlen",
    german_present_first_person: "empfahl",
    german_past_participle: "empfohlen",
    auxiliary_verb: "haben",
  },
  {
    id: 11,
    hungarian: "érezni",
    german_infinitive: "empfinden",
    german_present_first_person: "empfand",
    german_past_participle: "empfunden",
    auxiliary_verb: "haben",
  },
  {
    id: 12,
    hungarian: "enni",
    german_infinitive: "essen",
    german_present_first_person: "aß",
    german_past_participle: "gegessen",
    auxiliary_verb: "haben",
  },
  {
    id: 13,
    hungarian: "utazni; vezetni",
    german_infinitive: "fahren",
    german_present_first_person: "fuhr",
    german_past_participle: "gefahren",
    auxiliary_verb: "haben/sein",
  },
  {
    id: 14,
    hungarian: "fogni",
    german_infinitive: "fangen",
    german_present_first_person: "fing",
    german_past_participle: "gefangen",
    auxiliary_verb: "haben",
  },
  {
    id: 15,
    hungarian: "találni",
    german_infinitive: "finden",
    german_present_first_person: "fand",
    german_past_participle: "gefunden",
    auxiliary_verb: "haben",
  },
  {
    id: 16,
    hungarian: "repülni",
    german_infinitive: "fliegen",
    german_present_first_person: "flog",
    german_past_participle: "geflogen",
    auxiliary_verb: "sein",
  },
  {
    id: 17,
    hungarian: "menekülni",
    german_infinitive: "fliehen",
    german_present_first_person: "floh",
    german_past_participle: "geflohen",
    auxiliary_verb: "sein",
  },
  {
    id: 18,
    hungarian: "folyni",
    german_infinitive: "fließen",
    german_present_first_person: "floss",
    german_past_participle: "geflossen",
    auxiliary_verb: "sein",
  },
  {
    id: 19,
    hungarian: "zabálni",
    german_infinitive: "fressen",
    german_present_first_person: "fraß",
    german_past_participle: "gefressen",
    auxiliary_verb: "haben",
  },
  {
    id: 20,
    hungarian: "fázni; megfagyni",
    german_infinitive: "frieren",
    german_present_first_person: "fror",
    german_past_participle: "gefroren",
    auxiliary_verb: "haben/sein",
  },
  {
    id: 21,
    hungarian: "adni",
    german_infinitive: "geben",
    german_present_first_person: "gab",
    german_past_participle: "gegeben",
    auxiliary_verb: "haben",
  },
  {
    id: 22,
    hungarian: "menni",
    german_infinitive: "gehen",
    german_present_first_person: "ging",
    german_past_participle: "gegangen",
    auxiliary_verb: "sein",
  },
  {
    id: 23,
    hungarian: "sikerülni",
    german_infinitive: "gelingen",
    german_present_first_person: "gelang",
    german_past_participle: "gelungen",
    auxiliary_verb: "sein",
  },
  {
    id: 24,
    hungarian: "érvényesnek lenni",
    german_infinitive: "gelten",
    german_present_first_person: "galt",
    german_past_participle: "gegolten",
    auxiliary_verb: "haben",
  },
  {
    id: 25,
    hungarian: "élvezni",
    german_infinitive: "genießen",
    german_present_first_person: "genoss",
    german_past_participle: "genossen",
    auxiliary_verb: "haben",
  },
  {
    id: 26,
    hungarian: "jutni; kerülni",
    german_infinitive: "geraten",
    german_present_first_person: "geriet",
    german_past_participle: "geraten",
    auxiliary_verb: "sein",
  },
  {
    id: 27,
    hungarian: "történni",
    german_infinitive: "geschehen",
    german_present_first_person: "geschah",
    german_past_participle: "geschehen",
    auxiliary_verb: "sein",
  },
  {
    id: 28,
    hungarian: "nyerni",
    german_infinitive: "gewinnen",
    german_present_first_person: "gewann",
    german_past_participle: "gewonnen",
    auxiliary_verb: "haben",
  },
  {
    id: 29,
    hungarian: "öntözni; önteni",
    german_infinitive: "gießen",
    german_present_first_person: "goss",
    german_past_participle: "gegossen",
    auxiliary_verb: "haben",
  },
  {
    id: 30,
    hungarian: "hasonlítani",
    german_infinitive: "gleichen",
    german_present_first_person: "glich",
    german_past_participle: "geglichen",
    auxiliary_verb: "haben",
  },
  {
    id: 31,
    hungarian: "csúszni",
    german_infinitive: "gleiten",
    german_present_first_person: "glitt",
    german_past_participle: "geglitten",
    auxiliary_verb: "sein",
  },
  {
    id: 32,
    hungarian: "ásni",
    german_infinitive: "graben",
    german_present_first_person: "grub",
    german_past_participle: "gegraben",
    auxiliary_verb: "haben",
  },
  {
    id: 33,
    hungarian: "megfogni",
    german_infinitive: "greifen",
    german_present_first_person: "griff",
    german_past_participle: "gegriffen",
    auxiliary_verb: "haben",
  },
  {
    id: 34,
    hungarian: "tartani",
    german_infinitive: "halten",
    german_present_first_person: "hielt",
    german_past_participle: "gehalten",
    auxiliary_verb: "haben",
  },
  {
    id: 35,
    hungarian: "lógni; függni",
    german_infinitive: "hängen",
    german_present_first_person: "hing",
    german_past_participle: "gehangen",
    auxiliary_verb: "haben",
  },
  {
    id: 36,
    hungarian: "emelni",
    german_infinitive: "heben",
    german_present_first_person: "hob",
    german_past_participle: "gehoben",
    auxiliary_verb: "haben",
  },
  {
    id: 37,
    hungarian: "segíteni",
    german_infinitive: "helfen",
    german_present_first_person: "half",
    german_past_participle: "geholfen",
    auxiliary_verb: "haben",
  },
  {
    id: 38,
    hungarian: "hangzani",
    german_infinitive: "klingen",
    german_present_first_person: "klang",
    german_past_participle: "geklungen",
    auxiliary_verb: "haben",
  },
  {
    id: 39,
    hungarian: "jönni",
    german_infinitive: "kommen",
    german_present_first_person: "kam",
    german_past_participle: "gekommen",
    auxiliary_verb: "sein",
  },
  {
    id: 40,
    hungarian: "rakni; betölteni",
    german_infinitive: "laden",
    german_present_first_person: "lud",
    german_past_participle: "geladen",
    auxiliary_verb: "haben",
  },
  {
    id: 41,
    hungarian: "hagyni",
    german_infinitive: "lassen",
    german_present_first_person: "ließ",
    german_past_participle: "gelassen",
    auxiliary_verb: "haben",
  },
  {
    id: 42,
    hungarian: "futni",
    german_infinitive: "laufen",
    german_present_first_person: "lief",
    german_past_participle: "gelaufen",
    auxiliary_verb: "sein",
  },
  {
    id: 43,
    hungarian: "szenvedni",
    german_infinitive: "leiden",
    german_present_first_person: "litt",
    german_past_participle: "gelitten",
    auxiliary_verb: "haben",
  },
  {
    id: 44,
    hungarian: "kölcsönadni",
    german_infinitive: "leihen",
    german_present_first_person: "lieh",
    german_past_participle: "geliehen",
    auxiliary_verb: "haben",
  },
  {
    id: 45,
    hungarian: "olvasni",
    german_infinitive: "lesen",
    german_present_first_person: "las",
    german_past_participle: "gelesen",
    auxiliary_verb: "haben",
  },
  {
    id: 46,
    hungarian: "feküdni",
    german_infinitive: "liegen",
    german_present_first_person: "lag",
    german_past_participle: "gelegen",
    auxiliary_verb: "haben",
  },
  {
    id: 47,
    hungarian: "hazudni",
    german_infinitive: "lügen",
    german_present_first_person: "log",
    german_past_participle: "gelogen",
    auxiliary_verb: "haben",
  },
  {
    id: 48,
    hungarian: "kerülni",
    german_infinitive: "meiden",
    german_present_first_person: "mied",
    german_past_participle: "gemieden",
    auxiliary_verb: "haben",
  },
  {
    id: 49,
    hungarian: "mérni",
    german_infinitive: "messen",
    german_present_first_person: "maß",
    german_past_participle: "gemessen",
    auxiliary_verb: "haben",
  },
  {
    id: 50,
    hungarian: "sikertelenné válni",
    german_infinitive: "misslingen",
    german_present_first_person: "misslang",
    german_past_participle: "misslungen",
    auxiliary_verb: "sein",
  },
  {
    id: 51,
    hungarian: "venni",
    german_infinitive: "nehmen",
    german_present_first_person: "nahm",
    german_past_participle: "genommen",
    auxiliary_verb: "haben",
  },
  {
    id: 52,
    hungarian: "fütyülni",
    german_infinitive: "pfeifen",
    german_present_first_person: "pfiff",
    german_past_participle: "gepfiffen",
    auxiliary_verb: "haben",
  },
  {
    id: 53,
    hungarian: "dicsérni",
    german_infinitive: "preisen",
    german_present_first_person: "pries",
    german_past_participle: "gepriesen",
    auxiliary_verb: "haben",
  },
  {
    id: 54,
    hungarian: "tanácsolni",
    german_infinitive: "raten",
    german_present_first_person: "riet",
    german_past_participle: "geraten",
    auxiliary_verb: "haben",
  },
  {
    id: 55,
    hungarian: "dörzsölni",
    german_infinitive: "reiben",
    german_present_first_person: "rieb",
    german_past_participle: "gerieben",
    auxiliary_verb: "haben",
  },
  {
    id: 56,
    hungarian: "szakítani",
    german_infinitive: "reißen",
    german_present_first_person: "riss",
    german_past_participle: "gerissen",
    auxiliary_verb: "haben",
  },
  {
    id: 57,
    hungarian: "lovagolni",
    german_infinitive: "reiten",
    german_present_first_person: "ritt",
    german_past_participle: "geritten",
    auxiliary_verb: "haben/sein",
  },
  {
    id: 58,
    hungarian: "szagolni",
    german_infinitive: "riechen",
    german_present_first_person: "roch",
    german_past_participle: "gerochen",
    auxiliary_verb: "haben",
  },
  {
    id: 59,
    hungarian: "kiáltani",
    german_infinitive: "rufen",
    german_present_first_person: "rief",
    german_past_participle: "gerufen",
    auxiliary_verb: "haben",
  },
  {
    id: 60,
    hungarian: "iszik (állatokról)",
    german_infinitive: "saufen",
    german_present_first_person: "soff",
    german_past_participle: "gesoffen",
    auxiliary_verb: "haben",
  },
  {
    id: 61,
    hungarian: "szívni",
    german_infinitive: "saugen",
    german_present_first_person: "sog",
    german_past_participle: "gesogen",
    auxiliary_verb: "haben",
  },
  {
    id: 62,
    hungarian: "teremteni",
    german_infinitive: "schaffen",
    german_present_first_person: "schuf",
    german_past_participle: "geschaffen",
    auxiliary_verb: "haben",
  },
  {
    id: 63,
    hungarian: "elválasztani",
    german_infinitive: "scheiden",
    german_present_first_person: "schied",
    german_past_participle: "geschieden",
    auxiliary_verb: "haben/sein",
  },
  {
    id: 64,
    hungarian: "sütni",
    german_infinitive: "scheinen",
    german_present_first_person: "schien",
    german_past_participle: "geschienen",
    auxiliary_verb: "haben",
  },
  {
    id: 65,
    hungarian: "szidni",
    german_infinitive: "schelten",
    german_present_first_person: "schalt",
    german_past_participle: "gescholten",
    auxiliary_verb: "haben",
  },
  {
    id: 66,
    hungarian: "tolni",
    german_infinitive: "schieben",
    german_present_first_person: "schob",
    german_past_participle: "geschoben",
    auxiliary_verb: "haben",
  },
  {
    id: 67,
    hungarian: "aludni",
    german_infinitive: "schlafen",
    german_present_first_person: "schlief",
    german_past_participle: "geschlafen",
    auxiliary_verb: "haben",
  },
  {
    id: 68,
    hungarian: "ütni",
    german_infinitive: "schlagen",
    german_present_first_person: "schlug",
    german_past_participle: "geschlagen",
    auxiliary_verb: "haben",
  },
  {
    id: 69,
    hungarian: "bezárni",
    german_infinitive: "schließen",
    german_present_first_person: "schloss",
    german_past_participle: "geschlossen",
    auxiliary_verb: "haben",
  },
  {
    id: 70,
    hungarian: "olvadni",
    german_infinitive: "schmelzen",
    german_present_first_person: "schmolz",
    german_past_participle: "geschmolzen",
    auxiliary_verb: "haben/sein",
  },
  {
    id: 71,
    hungarian: "vágni",
    german_infinitive: "schneiden",
    german_present_first_person: "schnitt",
    german_past_participle: "geschnitten",
    auxiliary_verb: "haben",
  },
  {
    id: 72,
    hungarian: "megijeszteni",
    german_infinitive: "schrecken",
    german_present_first_person: "schrak",
    german_past_participle: "geschrocken",
    auxiliary_verb: "haben",
  },
  {
    id: 73,
    hungarian: "írni",
    german_infinitive: "schreiben",
    german_present_first_person: "schrieb",
    german_past_participle: "geschrieben",
    auxiliary_verb: "haben",
  },
  {
    id: 74,
    hungarian: "kiabálni",
    german_infinitive: "schreien",
    german_present_first_person: "schrie",
    german_past_participle: "geschrien",
    auxiliary_verb: "haben",
  },
];



