import { VocabularyWord } from "./vocabulary";

export const vocabularyApril: VocabularyWord[] = [
  // ===== VERBS =====
  {
    id: 2001,
    german: "sparen",
    hungarian: "spórolni; megtakarítani",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "spart",
      preterite: "sparte",
      perfect: "hat gespart",
    },
  },
  {
    id: 2002,
    german: "verlieren",
    hungarian: "elveszíteni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "verliert",
      preterite: "verlor",
      perfect: "hat verloren",
    },
  },
  {
    id: 2003,
    german: "ändern",
    hungarian: "változtatni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "ändert",
      preterite: "änderte",
      perfect: "hat geändert",
    },
  },
  {
    id: 2004,
    german: "ausgeben",
    hungarian: "kiadni (pénzt költeni)",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "gibt aus",
      preterite: "gab aus",
      perfect: "hat ausgegeben",
    },
  },
  {
    id: 2005,
    german: "reden",
    hungarian: "beszélni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "redet",
      preterite: "redete",
      perfect: "hat geredet",
    },
  },
  {
    id: 2006,
    german: "mitmachen",
    hungarian: "részt venni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "macht mit",
      preterite: "machte mit",
      perfect: "hat mitgemacht",
    },
  },
  {
    id: 2007,
    german: "brauchen",
    hungarian: "szüksége van",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "braucht",
      preterite: "brauchte",
      perfect: "hat gebraucht",
    },
  },
  {
    id: 2008,
    german: "entscheiden",
    hungarian: "eldönteni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "entscheidet",
      preterite: "entschied",
      perfect: "hat entschieden",
    },
  },
  {
    id: 2009,
    german: "klappen",
    hungarian: "sikerülni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "klappt",
      preterite: "klappte",
      perfect: "hat geklappt",
    },
  },
  {
    id: 2010,
    german: "denken",
    hungarian: "gondolkodni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "denkt",
      preterite: "dachte",
      perfect: "hat gedacht",
    },
  },
  {
    id: 2011,
    german: "sterben",
    hungarian: "meghalni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "stirbt",
      preterite: "starb",
      perfect: "ist gestorben",
    },
  },
  {
    id: 2012,
    german: "sich freuen",
    hungarian: "örülni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "freut sich",
      preterite: "freute sich",
      perfect: "hat sich gefreut",
    },
    note: "sich freuen über = örülni vminek (megtörtént); sich freuen auf = előre örülni",
  },
  {
    id: 2013,
    german: "retten",
    hungarian: "megmenteni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "rettet",
      preterite: "rettete",
      perfect: "hat gerettet",
    },
  },
  {
    id: 2014,
    german: "dauern",
    hungarian: "tartani (időben)",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "dauert",
      preterite: "dauerte",
      perfect: "hat gedauert",
    },
  },
  {
    id: 2015,
    german: "ziehen",
    hungarian: "húzni; vonszolni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "zieht",
      preterite: "zog",
      perfect: "hat gezogen",
    },
  },
  {
    id: 2016,
    german: "stranden",
    hungarian: "megrekedni, partra vetődni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "strandet",
      preterite: "strandete",
      perfect: "ist gestrandet",
    },
  },
  {
    id: 2017,
    german: "liegen",
    hungarian: "feküdni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "liegt",
      preterite: "lag",
      perfect: "hat gelegen",
    },
  },
  {
    id: 2018,
    german: "versuchen",
    hungarian: "megpróbálni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "versucht",
      preterite: "versuchte",
      perfect: "hat versucht",
    },
  },
  {
    id: 2019,
    german: "scheinen",
    hungarian: "sütni (nap); tűnni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "scheint",
      preterite: "schien",
      perfect: "hat geschienen",
    },
  },
  {
    id: 2020,
    german: "hoffen",
    hungarian: "remélni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "hofft",
      preterite: "hoffte",
      perfect: "hat gehofft",
    },
  },
  {
    id: 2021,
    german: "sich einigen",
    hungarian: "megegyezni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "einigt sich",
      preterite: "einigte sich",
      perfect: "hat sich geeinigt",
    },
  },
  {
    id: 2022,
    german: "beobachten",
    hungarian: "megfigyelni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "beobachtet",
      preterite: "beobachtete",
      perfect: "hat beobachtet",
    },
  },
  {
    id: 2023,
    german: "beeindrucken",
    hungarian: "lenyűgözni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "beeindruckt",
      preterite: "beeindruckte",
      perfect: "hat beeindruckt",
    },
  },
  {
    id: 2024,
    german: "bezahlen",
    hungarian: "fizetni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "bezahlt",
      preterite: "bezahlte",
      perfect: "hat bezahlt",
    },
  },
  {
    id: 2025,
    german: "bekommen",
    hungarian: "kapni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "bekommt",
      preterite: "bekam",
      perfect: "hat bekommen",
    },
  },
  {
    id: 2026,
    german: "besuchen",
    hungarian: "meglátogatni",
    type: "verb",
    month: "april",
    verbForms: {
      present_3rd: "besucht",
      preterite: "besuchte",
      perfect: "hat besucht",
    },
  },

  // ===== NOUNS =====
  {
    id: 2101,
    german: "Nachricht",
    hungarian: "hír",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Nachrichten",
  },
  {
    id: 2102,
    german: "Versicherung",
    hungarian: "biztosítás",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Versicherungen",
  },
  {
    id: 2103,
    german: "Krankenversicherung",
    hungarian: "egészségbiztosítás",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Krankenversicherungen",
  },
  {
    id: 2104,
    german: "Regierung",
    hungarian: "kormány",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Regierungen",
  },
  {
    id: 2105,
    german: "Haushalt",
    hungarian: "háztartás; költségvetés",
    type: "noun",
    month: "april",
    article: "der",
    plural: "Haushalte",
  },
  {
    id: 2106,
    german: "Schulden",
    hungarian: "adósságok",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Schulden",
    note: "Csak többes számban használjuk",
  },
  {
    id: 2107,
    german: "Besuch",
    hungarian: "látogatás",
    type: "noun",
    month: "april",
    article: "der",
    plural: "Besuche",
  },
  {
    id: 2108,
    german: "Wal",
    hungarian: "bálna",
    type: "noun",
    month: "april",
    article: "der",
    plural: "Wale",
  },
  {
    id: 2109,
    german: "Medikament",
    hungarian: "gyógyszer",
    type: "noun",
    month: "april",
    article: "das",
    plural: "Medikamente",
  },
  {
    id: 2110,
    german: "Hersteller",
    hungarian: "gyártó",
    type: "noun",
    month: "april",
    article: "der",
    plural: "Hersteller",
  },
  {
    id: 2111,
    german: "Gesetz",
    hungarian: "törvény",
    type: "noun",
    month: "april",
    article: "das",
    plural: "Gesetze",
  },
  {
    id: 2112,
    german: "Rente",
    hungarian: "nyugdíj",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Renten",
  },
  {
    id: 2113,
    german: "Krieg",
    hungarian: "háború",
    type: "noun",
    month: "april",
    article: "der",
    plural: "Kriege",
  },
  {
    id: 2114,
    german: "Krise",
    hungarian: "válság",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Krisen",
  },
  {
    id: 2115,
    german: "Applaus",
    hungarian: "taps",
    type: "noun",
    month: "april",
    article: "der",
  },
  {
    id: 2116,
    german: "Politiker",
    hungarian: "politikus",
    type: "noun",
    month: "april",
    article: "der",
    plural: "Politiker",
  },
  {
    id: 2117,
    german: "König",
    hungarian: "király",
    type: "noun",
    month: "april",
    article: "der",
    plural: "Könige",
  },
  {
    id: 2118,
    german: "Boden",
    hungarian: "talaj, padló",
    type: "noun",
    month: "april",
    article: "der",
    plural: "Böden",
  },
  {
    id: 2119,
    german: "Schiff",
    hungarian: "hajó",
    type: "noun",
    month: "april",
    article: "das",
    plural: "Schiffe",
  },
  {
    id: 2120,
    german: "Welle",
    hungarian: "hullám",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Wellen",
  },
  {
    id: 2121,
    german: "Wind",
    hungarian: "szél",
    type: "noun",
    month: "april",
    article: "der",
    plural: "Winde",
  },
  {
    id: 2122,
    german: "Richtung",
    hungarian: "irány",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Richtungen",
  },
  {
    id: 2123,
    german: "Experte",
    hungarian: "szakértő",
    type: "noun",
    month: "april",
    article: "der",
    plural: "Experten",
  },
  {
    id: 2124,
    german: "Fußballmannschaft",
    hungarian: "futballcsapat",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Fußballmannschaften",
  },
  {
    id: 2125,
    german: "Sonne",
    hungarian: "nap (égitest)",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Sonnen",
  },
  {
    id: 2126,
    german: "Wolke",
    hungarian: "felhő",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Wolken",
  },
  {
    id: 2127,
    german: "Sieger",
    hungarian: "győztes",
    type: "noun",
    month: "april",
    article: "der",
    plural: "Sieger",
  },
  {
    id: 2128,
    german: "Gerechtigkeit",
    hungarian: "igazságosság",
    type: "noun",
    month: "april",
    article: "die",
  },
  {
    id: 2129,
    german: "Beobachter",
    hungarian: "megfigyelő",
    type: "noun",
    month: "april",
    article: "der",
    plural: "Beobachter",
  },
  {
    id: 2130,
    german: "Meinung",
    hungarian: "vélemény",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Meinungen",
  },
  {
    id: 2131,
    german: "Hilfe",
    hungarian: "segítség",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Hilfen",
  },
  {
    id: 2132,
    german: "Staat",
    hungarian: "állam",
    type: "noun",
    month: "april",
    article: "der",
    plural: "Staaten",
  },
  {
    id: 2133,
    german: "Verteidigung",
    hungarian: "védelem",
    type: "noun",
    month: "april",
    article: "die",
  },
  {
    id: 2134,
    german: "Bereich",
    hungarian: "terület, részleg",
    type: "noun",
    month: "april",
    article: "der",
    plural: "Bereiche",
  },
  {
    id: 2135,
    german: "Arbeit",
    hungarian: "munka",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Arbeiten",
  },
  {
    id: 2136,
    german: "Zuckersteuer",
    hungarian: "cukoradó",
    type: "noun",
    month: "april",
    article: "die",
    plural: "Zuckersteuern",
  },

  // ===== ADJECTIVES =====
  { id: 2201, german: "krank", hungarian: "beteg", type: "adjective", month: "april" },
  { id: 2202, german: "zufrieden", hungarian: "elégedett", type: "adjective", month: "april" },
  { id: 2203, german: "schwach", hungarian: "gyenge", type: "adjective", month: "april" },
  { id: 2204, german: "weit", hungarian: "távoli, messzi", type: "adjective", month: "april" },
  { id: 2205, german: "verantwortlich", hungarian: "felelős", type: "adjective", month: "april" },
  { id: 2206, german: "unterschiedlich", hungarian: "eltérő, különböző", type: "adjective", month: "april" },
  { id: 2207, german: "teuer", hungarian: "drága", type: "adjective", month: "april" },
  { id: 2208, german: "wichtig", hungarian: "fontos", type: "adjective", month: "april" },

  // ===== OTHER =====
  { id: 2301, german: "fast", hungarian: "majdnem", type: "other", month: "april" },
  { id: 2302, german: "deshalb", hungarian: "ezért", type: "other", month: "april" },
  { id: 2303, german: "dazu", hungarian: "hozzá; ehhez", type: "other", month: "april" },
  { id: 2304, german: "dabei", hungarian: "eközben, mellette", type: "other", month: "april" },
  { id: 2305, german: "durch", hungarian: "át, keresztül", type: "other", month: "april" },
  { id: 2306, german: "weniger", hungarian: "kevesebb", type: "other", month: "april" },
  { id: 2307, german: "außerdem", hungarian: "ezenkívül", type: "other", month: "april" },
  { id: 2308, german: "bald", hungarian: "hamarosan", type: "other", month: "april" },
  { id: 2309, german: "vielleicht", hungarian: "talán", type: "other", month: "april" },
  { id: 2310, german: "später", hungarian: "később", type: "other", month: "april" },
  { id: 2311, german: "einige", hungarian: "néhány", type: "other", month: "april" },
  { id: 2312, german: "genug", hungarian: "elég", type: "other", month: "april" },
  { id: 2313, german: "nämlich", hungarian: "tudniillik, ugyanis", type: "other", month: "april" },
  { id: 2314, german: "zwar", hungarian: "ugyan; mégpedig", type: "other", month: "april" },
  { id: 2315, german: "manchmal", hungarian: "néha", type: "other", month: "april" },
  { id: 2316, german: "zuletzt", hungarian: "utoljára", type: "other", month: "april" },
  { id: 2317, german: "bisher", hungarian: "eddig", type: "other", month: "april" },
  { id: 2318, german: "geradezu", hungarian: "egyenesen, kifejezetten", type: "other", month: "april" },
  { id: 2319, german: "nun", hungarian: "most, akkor", type: "other", month: "april" },
  { id: 2320, german: "noch", hungarian: "még", type: "other", month: "april" },
  { id: 2321, german: "nur", hungarian: "csak", type: "other", month: "april" },
  { id: 2322, german: "gegen", hungarian: "ellen", type: "other", month: "april" },
];
