import { VocabularyWord } from "./vocabulary";

export const vocabularyMay: VocabularyWord[] = [
  // ===== VERBS =====
  {
    id: 1001,
    german: "einladen",
    hungarian: "meghívni",
    type: "verb",
    month: "may",
    verbForms: {
      present_3rd: "lädt ein",
      preterite: "lud ein",
      perfect: "hat eingeladen",
    },
  },
  {
    id: 1002,
    german: "wissen",
    hungarian: "tudni",
    type: "verb",
    month: "may",
    verbForms: {
      present_3rd: "weiß",
      preterite: "wusste",
      perfect: "hat gewusst",
    },
  },
  {
    id: 1003,
    german: "machen",
    hungarian: "csinálni",
    type: "verb",
    month: "may",
    verbForms: {
      present_3rd: "macht",
      preterite: "machte",
      perfect: "hat gemacht",
    },
  },
  {
    id: 1004,
    german: "trainieren",
    hungarian: "edzeni",
    type: "verb",
    month: "may",
    verbForms: {
      present_3rd: "trainiert",
      preterite: "trainierte",
      perfect: "hat trainiert",
    },
    note: "-ieren végű igéknél nincs ge- a múlt időben",
  },
  {
    id: 1005,
    german: "eintreten",
    hungarian: "belépni",
    type: "verb",
    month: "may",
    verbForms: {
      present_3rd: "tritt ein",
      preterite: "trat ein",
      perfect: "ist eingetreten",
    },
  },
  {
    id: 1006,
    german: "halten",
    hungarian: "tartani",
    type: "verb",
    month: "may",
    verbForms: {
      present_3rd: "hält",
      preterite: "hielt",
      perfect: "hat gehalten",
    },
  },
  {
    id: 1007,
    german: "sein",
    hungarian: "lenni",
    type: "verb",
    month: "may",
    verbForms: {
      present_3rd: "ist",
      preterite: "war",
      perfect: "ist gewesen",
    },
  },
  {
    id: 1008,
    german: "herumfahren",
    hungarian: "utazgatni össze-vissza",
    type: "verb",
    month: "may",
    verbForms: {
      present_3rd: "fährt herum",
      preterite: "fuhr herum",
      perfect: "ist herumgefahren",
    },
  },
  {
    id: 1009,
    german: "auftreten",
    hungarian: "fellépni",
    type: "verb",
    month: "may",
    verbForms: {
      present_3rd: "tritt auf",
      preterite: "trat auf",
      perfect: "ist aufgetreten",
    },
  },
  {
    id: 1010,
    german: "sich vorstellen",
    hungarian: "elképzelni; bemutatkozni",
    type: "verb",
    month: "may",
    verbForms: {
      present_3rd: "stellt sich vor",
      preterite: "stellte sich vor",
      perfect: "hat sich vorgestellt",
    },
  },
  {
    id: 1011,
    german: "faszinieren",
    hungarian: "elbűvölni",
    type: "verb",
    month: "may",
    verbForms: {
      present_3rd: "fasziniert",
      preterite: "faszinierte",
      perfect: "hat fasziniert",
    },
  },
  {
    id: 1012,
    german: "springen",
    hungarian: "ugrani",
    type: "verb",
    month: "may",
    verbForms: {
      present_3rd: "springt",
      preterite: "sprang",
      perfect: "ist gesprungen",
    },
  },

  // ===== NOUNS =====
  {
    id: 1101,
    german: "Veranstaltung",
    hungarian: "rendezvény, fellépés",
    type: "noun",
    month: "may",
    article: "die",
    plural: "Veranstaltungen",
  },
  {
    id: 1102,
    german: "Möglichkeit",
    hungarian: "lehetőség",
    type: "noun",
    month: "may",
    article: "die",
    plural: "Möglichkeiten",
  },
  {
    id: 1103,
    german: "Gefühl",
    hungarian: "érzés",
    type: "noun",
    month: "may",
    article: "das",
    plural: "Gefühle",
  },
  {
    id: 1104,
    german: "Vater",
    hungarian: "apa",
    type: "noun",
    month: "may",
    article: "der",
    plural: "Väter",
  },
  {
    id: 1105,
    german: "Sohn",
    hungarian: "fiú (utód)",
    type: "noun",
    month: "may",
    article: "der",
    plural: "Söhne",
  },
  {
    id: 1106,
    german: "Mann",
    hungarian: "férfi",
    type: "noun",
    month: "may",
    article: "der",
    plural: "Männer",
  },
  {
    id: 1107,
    german: "Baum",
    hungarian: "fa",
    type: "noun",
    month: "may",
    article: "der",
    plural: "Bäume",
  },
  {
    id: 1108,
    german: "Hustensaft",
    hungarian: "köhögés elleni szirup",
    type: "noun",
    month: "may",
    article: "der",
    plural: "Hustensäfte",
  },
  {
    id: 1109,
    german: "Mathetest",
    hungarian: "matek dolgozat",
    type: "noun",
    month: "may",
    article: "der",
    plural: "Mathetests",
  },
  {
    id: 1110,
    german: "Sessel",
    hungarian: "fotel",
    type: "noun",
    month: "may",
    article: "der",
    plural: "Sessel",
  },
  {
    id: 1111,
    german: "Tür",
    hungarian: "ajtó",
    type: "noun",
    month: "may",
    article: "die",
    plural: "Türen",
  },
  {
    id: 1112,
    german: "Mädchen",
    hungarian: "lány",
    type: "noun",
    month: "may",
    article: "das",
    plural: "Mädchen",
  },
  {
    id: 1113,
    german: "Kleid",
    hungarian: "ruha",
    type: "noun",
    month: "may",
    article: "das",
    plural: "Kleider",
  },
  {
    id: 1114,
    german: "Kind",
    hungarian: "gyerek",
    type: "noun",
    month: "may",
    article: "das",
    plural: "Kinder",
  },
  {
    id: 1115,
    german: "Fahrrad",
    hungarian: "bicikli",
    type: "noun",
    month: "may",
    article: "das",
    plural: "Fahrräder",
  },
  {
    id: 1116,
    german: "Geschirr",
    hungarian: "edények, étkészlet",
    type: "noun",
    month: "may",
    article: "das",
  },
  {
    id: 1117,
    german: "Student",
    hungarian: "diák",
    type: "noun",
    month: "may",
    article: "der",
    plural: "Studenten",
  },
  {
    id: 1118,
    german: "Gast",
    hungarian: "vendég",
    type: "noun",
    month: "may",
    article: "der",
    plural: "Gäste",
  },
  {
    id: 1119,
    german: "Bohne",
    hungarian: "bab",
    type: "noun",
    month: "may",
    article: "die",
    plural: "Bohnen",
  },
  {
    id: 1120,
    german: "Schuh",
    hungarian: "cipő",
    type: "noun",
    month: "may",
    article: "der",
    plural: "Schuhe",
  },
  {
    id: 1121,
    german: "Koch",
    hungarian: "szakács",
    type: "noun",
    month: "may",
    article: "der",
    plural: "Köche",
  },

  // ===== ADJECTIVES =====
  { id: 1201, german: "schmutzig", hungarian: "koszos", type: "adjective", month: "may" },
  { id: 1202, german: "schwierig", hungarian: "nehéz", type: "adjective", month: "may" },
  { id: 1203, german: "hübsch", hungarian: "csinos", type: "adjective", month: "may" },
  { id: 1204, german: "verwöhnt", hungarian: "elkényeztetett", type: "adjective", month: "may" },
  { id: 1205, german: "bitter", hungarian: "keserű", type: "adjective", month: "may" },
  { id: 1206, german: "streng", hungarian: "szigorú", type: "adjective", month: "may" },
  { id: 1207, german: "faul", hungarian: "lusta", type: "adjective", month: "may" },
  { id: 1208, german: "ängstlich", hungarian: "félénk", type: "adjective", month: "may" },
  { id: 1209, german: "stürmisch", hungarian: "viharos", type: "adjective", month: "may" },
  { id: 1210, german: "dunkelrot", hungarian: "sötétvörös", type: "adjective", month: "may" },
  { id: 1211, german: "frech", hungarian: "pimasz", type: "adjective", month: "may" },
  { id: 1212, german: "fremd", hungarian: "idegen", type: "adjective", month: "may" },
  { id: 1213, german: "langsam", hungarian: "lassú", type: "adjective", month: "may" },
  { id: 1214, german: "hungrig", hungarian: "éhes", type: "adjective", month: "may" },
  { id: 1215, german: "verwundet", hungarian: "sérült, sebesült", type: "adjective", month: "may" },
  { id: 1216, german: "schmal", hungarian: "szűk, keskeny", type: "adjective", month: "may" },
  { id: 1217, german: "fleißig", hungarian: "szorgalmas", type: "adjective", month: "may" },
  { id: 1218, german: "hellblau", hungarian: "világoskék", type: "adjective", month: "may" },
  { id: 1219, german: "breit", hungarian: "széles", type: "adjective", month: "may" },
  { id: 1220, german: "arbeitslos", hungarian: "munkanélküli", type: "adjective", month: "may" },
  { id: 1221, german: "verschieden", hungarian: "különböző", type: "adjective", month: "may" },

  // ===== OTHER =====
  { id: 1301, german: "früher", hungarian: "korábban", type: "other", month: "may" },
  { id: 1302, german: "ganz", hungarian: "teljes, egész", type: "other", month: "may" },
  { id: 1303, german: "irgendwann", hungarian: "valamikor", type: "other", month: "may" },
  { id: 1304, german: "jederzeit", hungarian: "bármikor", type: "other", month: "may" },
  { id: 1305, german: "unterwegs", hungarian: "úton (lenni)", type: "other", month: "may" },
];
